#!/bin/bash
yum update -y
yum install -y httpd
systemctl start httpd.service
systemctl enable httpd.service
echo "<h1> Welcome to AWS EC2 Training with Jerry Bame assisted by Wills</h1>" > /var/www/html/index.html


-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Alternative user-data [This will show the AZ of the EC2 instance] 

#!/bin/bash
#Use this for your user data (Script from top to bottom)
#install httpd (Linux 2 version)
yum update -y
yum install -y httpd
systemctl start httpd
systemctl enable httpd
echo "<h1> Welcome to Bame Tech from $(hostname -f)</h1>" > /var/www/html/index.html


--------------------------------------------------------------------------------------------------------------------------------- Ubuntu Server User-Data ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#!/bin/bash
yes | sudo apt update
yes | sudo apt install apache2
echo "<h1>Server Details</h1><p><strong>Hostname:</strong> $(hostname)</p><p><strong>IP Address:</strong> $(hostname -I | cut -d' ' -f1)</p>" > /var/www/html/index.html
sudo systemctl restart apache2



