#!/bin/bash
yum update -y
yum install -y httpd
systemctl start httpd.service
systemctl enable httpd.service
cd /var/www/html
touch index.html
echo "<h1> Welcome to AWS EC2 Training with Jerry Bame assisted by Wills</h1>" > index.html




